# -*- coding: utf-8 -*-
"""Agent_Demo_Day_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Irdns8TZ9k4NnCTQqXGDsEZxxNHUieQ4
"""

import google.generativeai as genai
import os
from google.colab import userdata


# Get the API key from the environment variable set by the Colab notebook
api_key = os.environ.get('YOUR_API_KEY')

if not api_key:
    raise ValueError("GOOGLE_API_KEY environment variable not set. Please ensure it's set before running the app.")

# Configure the generative AI model with the retrieved API key
genai.configure(api_key=api_key)


from pypdf import PdfReader

folder = "Your Source Folder"


def load_pdfs(folder):
    texts = []
    for file in os.listdir(folder):
        if file.endswith(".pdf"):
            reader = PdfReader(os.path.join(folder, file))
            for page in reader.pages:
                texts.append(page.extract_text())
    return texts


import json

def load_notebooks(folder):
    texts = []
    for file in os.listdir(folder):
        if file.endswith(".ipynb"):
            with open(os.path.join(folder, file)) as f:
                nb = json.load(f)
                for cell in nb["cells"]:
                    if cell["cell_type"] == "markdown":
                        texts.append(" ".join(cell["source"]))
    return texts


def chunk_text(texts, chunk_size=800, overlap=100):
    chunks = []
    for text in texts:
        start = 0
        while start < len(text):
            chunks.append(text[start:start+chunk_size])
            start += chunk_size - overlap
    return chunks


from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

embedder = SentenceTransformer("all-MiniLM-L6-v2")


# Create vector index

pdf_texts = load_pdfs(folder)
notebook_texts = load_notebooks(folder)
all_texts = pdf_texts + notebook_texts
chunks = chunk_text(all_texts)

embeddings = embedder.encode(chunks, convert_to_numpy=True)

index = faiss.IndexFlatL2(embeddings.shape[1])
index.add(embeddings)


def retrieve_with_score(question, k=4):
    q_emb = embedder.encode([question])
    distances, idxs = index.search(q_emb, k)

    retrieved_chunks = [chunks[i] for i in idxs[0]]
    avg_distance = distances[0].mean()

    return retrieved_chunks, avg_distance



# Select Model
model = genai.GenerativeModel("gemini-2.5-flash-lite") # gemini-2.5-flash, gemini-2.5-flash-lite, gemini-3-flash-preview, gemini-3-pro-preview


# Define a relevance threshold
RELEVANCE_THRESHOLD = 1.2  # you can tune this


def ask_agent(question):
    retrieved_chunks, score = retrieve_with_score(question)

    if score < RELEVANCE_THRESHOLD:
        # Grounded answer
        context = "\n".join(retrieved_chunks)

        prompt = f"""
You are a workshop assistant.
If the context partially answers the question, explain cautiously.
If it does not, say "Not covered in workshop materials."

Context:
{context}

Question:
{question}
"""
        response = model.generate_content(prompt)
        return response.text

    else:
        # General answer (explicitly marked)
        prefix = (
            "Though this particular topic may not be covered in the workshop, "
            "for the purpose of this ReAct demo I’m giving a brief answer.\n\n"
        )

        prompt = f"""
Answer the following question briefly and at a high level.

Question:
{question}
"""
        response = model.generate_content(prompt)
        return prefix + response.text