# -*- coding: utf-8 -*-
"""app_agent_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1elnHXe9zM21znQ4ZkL6OEJxQGQ-Krr
"""

import streamlit as st

import sys
# Add the directory containing the notebook to sys.path
sys.path.append("Your Content Location")

from agent_demo_day_3 import ask_agent, retrieve_with_score, RELEVANCE_THRESHOLD

st.set_page_config(
    page_title="Workshop Agent",
    page_icon="🤖",
    layout="centered"
)

st.title("🤖 Workshop Assistant (ReAct-lite Agent)")
st.caption(
    "A grounded AI agent that answers questions using workshop materials "
    "(PDFs & notebooks)."
)

st.markdown("---")

question = st.text_input(
    "Ask a question about the workshop:",
    placeholder="e.g. How did CNNs connect to image generation models?"
)

if st.button("Ask Agent"):
    if not question.strip():
        st.warning("Please enter a question.")
    else:
        with st.spinner("Agent reasoning..."):
            # Check grounding
            _, score = retrieve_with_score(question)

            if score < RELEVANCE_THRESHOLD:
                st.success("🔍 Grounded Answer (used workshop materials)")
            else:
                st.info("💬 General Answer (no workshop grounding found)")

            answer = ask_agent(question)

        st.markdown("### 🧠 Agent Response")
        st.write(answer)

st.markdown("---")

with st.expander("ℹ️ How this Agent Works"):
    st.markdown(
        """
        **This is a simple ReAct-style agent:**

        1. Checks workshop documents (PDFs & notebooks)
        2. Decides whether grounding is available
        3. Uses retrieval **only when relevant**
        4. Clearly signals grounded vs general answers

        No web access. No hallucinated knowledge.
        """
    )